-- MySQL Script generated by MySQL Workbench
-- qua 14 mai 2025 10:12:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema durval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema durval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `durval` ;
USE `durval` ;

-- -----------------------------------------------------
-- Table `durval`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durval`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durval`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durval`.`Artista` (
  `idArtista` INT NOT NULL,
  `nome_artista` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durval`.`Disco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durval`.`Disco` (
  `idDisco` INT NOT NULL,
  `nome_disco` VARCHAR(80) NULL,
  `valor` FLOAT NULL,
  `Artista_idArtista` INT NOT NULL,
  PRIMARY KEY (`idDisco`, `Artista_idArtista`),
  INDEX `fk_Disco_Artista_idx` (`Artista_idArtista` ASC) VISIBLE,
  CONSTRAINT `fk_Disco_Artista`
    FOREIGN KEY (`Artista_idArtista`)
    REFERENCES `durval`.`Artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durval`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durval`.`Venda` (
  `idVenda` INT NOT NULL,
  `data` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `Cliente_idCliente`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `durval`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `durval`.`itemcompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `durval`.`itemcompra` (
  `iditemcompra` INT NOT NULL,
  `Disco_idDisco` INT NOT NULL,
  `Disco_Artista_idArtista` INT NOT NULL,
  `Venda_idVenda` INT NOT NULL,
  PRIMARY KEY (`iditemcompra`, `Disco_idDisco`, `Disco_Artista_idArtista`, `Venda_idVenda`),
  INDEX `fk_itemcompra_Disco1_idx` (`Disco_idDisco` ASC, `Disco_Artista_idArtista` ASC) VISIBLE,
  INDEX `fk_itemcompra_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  CONSTRAINT `fk_itemcompra_Disco1`
    FOREIGN KEY (`Disco_idDisco` , `Disco_Artista_idArtista`)
    REFERENCES `durval`.`Disco` (`idDisco` , `Artista_idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemcompra_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `durval`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
